import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script defer src="http://umami-u0occok.5.161.97.168.sslip.io/script.js" data-website-id="620f55fb-5a18-44a6-bf43-609a1eda6d49"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
